// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujxbqwnbxtivwkbkbotb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqeGJxd25ieHRpdndrYmtib3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MTczNDIsImV4cCI6MjA1NzI5MzM0Mn0.JoVRkPTfqZrykD0kmPZnS2BtI8FUwEz4HCsQO2QKrBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);